// <auto-generated />
using E_Commerce_Website.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace E_Commerce_Website.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250416105607_SeedProducts")]
    partial class SeedProducts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("E_Commerce_Website.Models.Product", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("ID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Description = "Cotton Shirt for comfort",
                            Image = "download.jfif",
                            Name = "Shirt",
                            Price = 599.0
                        },
                        new
                        {
                            ID = 2,
                            Description = "Cotton Shirt for comfort",
                            Image = "download.jfif",
                            Name = "Shirt",
                            Price = 599.0
                        },
                        new
                        {
                            ID = 3,
                            Description = "Cotton Shirt for comfort",
                            Image = "download.jfif",
                            Name = "Shirt",
                            Price = 599.0
                        },
                        new
                        {
                            ID = 4,
                            Description = "Cotton Shirt for comfort",
                            Image = "download.jfif",
                            Name = "Shirt",
                            Price = 599.0
                        },
                        new
                        {
                            ID = 5,
                            Description = "Cotton Shirt for comfort",
                            Image = "download.jfif",
                            Name = "Shirt",
                            Price = 599.0
                        },
                        new
                        {
                            ID = 6,
                            Description = "Cotton Shirt for comfort",
                            Image = "download.jfif",
                            Name = "Shirt",
                            Price = 599.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
